title: pdfpc
description: >-
  A presenter console with multi-monitor support for PDF files
baseurl: ""
url: ""
github_username: pdfpc
repository: pdfpc/pdfpc
github:
    repository_url: https://github.com/pdfpc/pdfpc
markdown: kramdown
theme: jekyll-theme-slate

